package com.goodworkalan.mix;

import java.util.Collection;

import com.goodworkalan.go.go.Artifact;
import com.goodworkalan.go.go.InputOutput;
import com.goodworkalan.go.go.PathPart;

/**
 * A project dependency.
 * 
 * @author Alan Gutierrez
 */
public interface Dependency {
    /**
     * Get the part parts for the dependency. The path parts are to be used to
     * create a <code>LibraryPath</code>.
     * 
     * @param project
     *            The project.
     * @return A collection of path parts.
     */
    public Collection<PathPart> getPathParts(Project project);

    /**
     * Get a collection of the immediate artifact dependencies.
     * 
     * @param project
     *            The project.
     * @return A collection of the immediate artifact dependencies.
     */
    public Collection<Artifact> getArtifacts(Project project);

    /**
     * Make the dependency. If the dependency is generated by this project the
     * make task will be invoked.
     * 
     * @param io
     *            The input/output streams.
     * @param project
     *            The project.
     */
    public void make(InputOutput io, Project project);
}
